### ISSUE TITLE
Build failing at Broadcom WLAN drivers

### ISSUE THREAD

**Issue by muhammadfahadbaig** [HuaweiHonor4C/android_device_huawei_hi6210sft#1]
Here is the log file:
http://hastebin.com/opagequvuv.coffee

@olrak2 @XePeleato Any idea about this bug since you've build AOSP 6.0.

**Comment by olrak2** [comment]
I have never build for android 6.0, always 5.1. 5.1 has more stable source code.

Only build once a kernel for 6.0 on the stock huawei firmware.

Maybe use my new ramdisk with support for wifi.  You also need to add wpa_supplicant_hisi.so and p2p_supplicant_hisi because those are used for the wifi.

**Comment by olrak2** [comment]
Maybe another sollution.  remove the config_driver_... options from your code.

Try to copy this code for wifi in boardconfig.  it's for android 6.0

https://github.com/omnirom/android_device_huawei_angler/blob/android-6.0/BoardConfig.mk

**Comment by muhammadfahadbaig** [comment]
This issue is now fixed. I'll close it once the fix is merged.

**Comment by muhammadfahadbaig** [comment]
0831b47eb06cf50a38b6a20899b458674d03d054
